[project]
name = "com.Internet123.student-on-duty"
version = "1.0.0"
description = "一个显示今日值日生信息的插件"
authors = [
    {name = "月下的桃子"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["class-widgets-sdk"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
